/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: b7256b57c1016172039bb584b2a835fb)
// Runtime types generated with workerd@1.20260405.1 2026-04-07 nodejs_als
declare namespace Cloudflare {
	interface Env {
		CLOUDFLARE_API_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
